/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Especificação de bit forçado (input JS). */
export interface JsForcedBit {
  /** Área de memória: "CIO", "WR", "HR", "AR" */
  area: string
  /** Endereço da word */
  address: number
  /** Posição do bit (0-15) */
  bit: number
  /** Especificação: "force_on", "force_off", "release" */
  spec: string
}
/** Especificação de leitura múltipla (input JS). */
export interface JsMultiReadSpec {
  /** Área de memória: "CIO", "WR", "HR", "DM", "AR" */
  area: string
  /** Endereço da word */
  address: number
  /** Posição do bit (opcional, null/undefined para leitura de word) */
  bit?: number
}
/** Porta UDP padrão do protocolo FINS. */
export const DEFAULT_FINS_PORT: number
/** Tamanho máximo do pacote FINS. */
export const MAX_PACKET_SIZE: number
/** Máximo de words por comando. */
export const MAX_WORDS_PER_COMMAND: number
/** Opções avançadas de configuração do cliente FINS. */
export interface JsClientOptions {
  /** Porta UDP (padrão: 9600) */
  port?: number
  /** Timeout em milissegundos (padrão: 2000) */
  timeoutMs?: number
  /** Número da rede de origem */
  sourceNetwork?: number
  /** Número da unidade de origem */
  sourceUnit?: number
  /** Número da rede de destino */
  destNetwork?: number
  /** Número da unidade de destino */
  destUnit?: number
}
/** Obtém o valor de um bit específico de uma word u16. */
export declare function getBit(value: number, bit: number): boolean
/** Define o valor de um bit específico em uma word u16. */
export declare function setBit(value: number, bit: number, on: boolean): number
/** Alterna o valor de um bit específico em uma word u16. */
export declare function toggleBit(value: number, bit: number): number
/** Converte uma word u16 em um array de 16 booleanos. */
export declare function wordToBits(value: number): Array<boolean>
/** Converte um array de booleanos para uma word u16. */
export declare function bitsToWord(bits: Array<boolean>): number
/** Retorna indices dos bits que estão ON em uma word. */
export declare function getOnBits(value: number): Array<number>
/** Conta quantos bits estão ON em uma word. */
export declare function countOnBits(value: number): number
/** Formata uma word como string binária (ex: "0b1010_0101_1100_0011"). */
export declare function formatBinary(value: number): string
/** Formata uma word como string hexadecimal (ex: "0xA5C3"). */
export declare function formatHex(value: number): string
/**
 * Cliente FINS para comunicação com PLCs Omron.
 *
 * Cada operação gera exatamente 1 request e 1 response UDP.
 * Sem retries automáticos, caching ou reconexão.
 */
export declare class FinsClient {
  /**
   * Cria um novo cliente FINS.
   *
   * @param host - Endereço IP do PLC (ex: "192.168.1.250")
   * @param sourceNode - Número do nó de origem (este cliente)
   * @param destNode - Número do nó de destino (o PLC)
   * @param options - Opções avançadas (opcional)
   */
  constructor(host: string, sourceNode: number, destNode: number, options?: JsClientOptions | undefined | null)
  /**
   * Lê words da memória do PLC (assíncrono).
   *
   * @param area - Área de memória ("DM", "CIO", "WR", "HR", "AR")
   * @param address - Endereço inicial
   * @param count - Quantidade de words para ler (1-999)
   * @returns Promise<number[]> - Array de valores u16
   */
  read(area: string, address: number, count: number): Promise<Array<number>>
  /**
   * Escreve words na memória do PLC (assíncrono).
   *
   * @param area - Área de memória ("DM", "CIO", "WR", "HR", "AR")
   * @param address - Endereço inicial
   * @param data - Array de valores u16 para escrever
   */
  write(area: string, address: number, data: Array<number>): Promise<void>
  /**
   * Lê um bit da memória do PLC (assíncrono).
   *
   * @param area - Área de memória ("CIO", "WR", "HR", "AR") — DM não suporta bits
   * @param address - Endereço da word
   * @param bit - Posição do bit (0-15)
   * @returns Promise<boolean>
   */
  readBit(area: string, address: number, bit: number): Promise<boolean>
  /**
   * Escreve um bit na memória do PLC (assíncrono).
   *
   * @param area - Área de memória ("CIO", "WR", "HR", "AR")
   * @param address - Endereço da word
   * @param bit - Posição do bit (0-15)
   * @param value - Valor do bit (true/false)
   */
  writeBit(area: string, address: number, bit: number, value: boolean): Promise<void>
  /**
   * Preenche uma região de memória com um valor (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial
   * @param count - Quantidade de words para preencher (1-999)
   * @param value - Valor u16 para preencher
   */
  fill(area: string, address: number, count: number, value: number): Promise<void>
  /**
   * Transfere dados de uma área de memória para outra (assíncrono).
   *
   * @param srcArea - Área de memória de origem
   * @param srcAddress - Endereço de origem
   * @param dstArea - Área de memória de destino
   * @param dstAddress - Endereço de destino
   * @param count - Quantidade de words para transferir
   */
  transfer(srcArea: string, srcAddress: number, dstArea: string, dstAddress: number, count: number): Promise<void>
  /**
   * Coloca o PLC em modo de execução (assíncrono).
   *
   * @param mode - Modo: "debug", "monitor" ou "run"
   */
  run(mode: string): Promise<void>
  /** Para o PLC (assíncrono). */
  stop(): Promise<void>
  /**
   * Força bits ON/OFF no PLC (assíncrono).
   *
   * @param specs - Array de especificações de bits forçados
   */
  forcedSetReset(specs: Array<JsForcedBit>): Promise<void>
  /** Cancela todos os bits forçados no PLC (assíncrono). */
  forcedSetResetCancel(): Promise<void>
  /**
   * Lê de múltiplas áreas de memória em uma única requisição (assíncrono).
   *
   * @param specs - Array de especificações de leitura
   * @returns Promise<number[]> - Array de valores u16
   */
  readMultiple(specs: Array<JsMultiReadSpec>): Promise<Array<number>>
  /**
   * Lê um valor f32 (REAL) de 2 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @returns Promise<number>
   */
  readF32(area: string, address: number): Promise<number>
  /**
   * Escreve um valor f32 (REAL) em 2 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @param value - Valor f32 para escrever
   */
  writeF32(area: string, address: number, value: number): Promise<void>
  /**
   * Lê um valor f64 (LREAL) de 4 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @returns Promise<number>
   */
  readF64(area: string, address: number): Promise<number>
  /**
   * Escreve um valor f64 (LREAL) em 4 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @param value - Valor f64 para escrever
   */
  writeF64(area: string, address: number, value: number): Promise<void>
  /**
   * Lê um valor i32 (DINT) de 2 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @returns Promise<number>
   */
  readI32(area: string, address: number): Promise<number>
  /**
   * Escreve um valor i32 (DINT) em 2 words consecutivas (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @param value - Valor i32 para escrever
   */
  writeI32(area: string, address: number, value: number): Promise<void>
  /**
   * Escreve uma string ASCII na memória do PLC (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @param value - String ASCII para escrever (máximo 1998 caracteres)
   */
  writeString(area: string, address: number, value: string): Promise<void>
  /**
   * Lê uma string ASCII da memória do PLC (assíncrono).
   *
   * @param area - Área de memória
   * @param address - Endereço inicial da word
   * @param wordCount - Quantidade de words para ler (1 word = 2 caracteres)
   * @returns Promise<string>
   */
  readString(area: string, address: number, wordCount: number): Promise<string>
}
